import { PrismaClient } from "@prisma/client";
import { randomBytes, scryptSync } from "node:crypto";
import { config } from "dotenv";

config({ path: ".env.local" });
config();

const prisma = new PrismaClient();

const seedTimestamp = new Date("2026-06-10T00:00:00.000Z");

function hashPassword(password) {
  const salt = randomBytes(16).toString("hex");
  const hash = scryptSync(password, salt, 64).toString("hex");

  return `scrypt:${salt}:${hash}`;
}

const users = [
  {
    username: "owner",
    password: "owner",
    role: "owner",
    displayName: "Owner",
    email: "owner@imo-meals.local",
  },
  {
    username: "member",
    password: "member",
    role: "member",
    displayName: "Member",
    email: "member@imo-meals.local",
  },
  {
    username: "readonly",
    password: "readonly",
    role: "readonly",
    displayName: "Readonly",
    email: "readonly@imo-meals.local",
  },
];

const foods = [
  {
    id: "food-001",
    name: "Arroz blanco",
    category: "Cereal",
    status: "allowed",
    tolerance: 5,
    notes: "Base neutra para comidas simples.",
    suggestedServing: "120 g, equivale a un bol pequeno de arroz cocido.",
    tags: ["bajo residuo", "sin gluten", "base"],
  },
  {
    id: "food-002",
    name: "Pechuga de pollo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Mejor a la plancha, horno o cocida con poca grasa.",
    suggestedServing: "120 g, equivale a un filete pequeno cocinado.",
    tags: ["proteina", "rapido", "salado"],
  },
  {
    id: "food-003",
    name: "Calabacin",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar sin piel y en racion pequena.",
    suggestedServing: "75 g, equivale a medio calabacin pequeno cocido.",
    tags: ["verdura", "fase prueba"],
  },
  {
    id: "food-004",
    name: "Huevo",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Util para desayunos y cenas rapidas.",
    suggestedServing: "1 unidad, huevo tamano M.",
    tags: ["proteina", "desayuno"],
  },
  {
    id: "food-005",
    name: "Aguacate",
    category: "Grasa",
    status: "caution",
    tolerance: 2,
    notes: "Puede ser pesado; revisar cantidad y momento del dia.",
    suggestedServing: "30 g, equivale a un cuarto de aguacate de tamano medio.",
    tags: ["grasa", "porcion controlada"],
  },
  {
    id: "food-006",
    name: "Cebolla",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de sintomas en fases restrictivas.",
    tags: ["fodmap", "evitar"],
  },
  {
    id: "food-007",
    name: "Yogur sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Introducir solo si hay buena tolerancia a lacteos.",
    tags: ["lacteo", "probio"],
  },
  {
    id: "food-008",
    name: "Platano verde",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Mejor en pequena cantidad y no demasiado maduro.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-009",
    name: "Patata cocida",
    category: "Tuberculo",
    status: "allowed",
    tolerance: 5,
    notes: "Opcion simple para comidas suaves.",
    tags: ["base", "sin gluten", "suave"],
  },
  {
    id: "food-010",
    name: "Boniato",
    category: "Tuberculo",
    status: "testing",
    tolerance: 3,
    notes: "Probar en racion pequena por su carga de carbohidrato.",
    tags: ["tuberculo", "porcion"],
  },
  {
    id: "food-011",
    name: "Quinoa",
    category: "Cereal",
    status: "testing",
    tolerance: 3,
    notes: "Lavar bien y probar como guarnicion pequena.",
    tags: ["sin gluten", "guarnicion"],
  },
  {
    id: "food-012",
    name: "Avena",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "La tolerancia puede variar mucho segun cantidad.",
    tags: ["fibra", "desayuno", "porcion"],
  },
  {
    id: "food-013",
    name: "Pan blanco",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "Revisar tolerancia individual y tipo de harina.",
    tags: ["gluten", "procesado"],
  },
  {
    id: "food-014",
    name: "Pan integral",
    category: "Cereal",
    status: "avoid",
    tolerance: 1,
    notes: "Puede ser mas fermentable por fibra y trigo.",
    tags: ["gluten", "fibra", "evitar"],
  },
  {
    id: "food-015",
    name: "Pasta de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Alternativa sencilla a pasta de trigo.",
    tags: ["sin gluten", "base"],
  },
  {
    id: "food-016",
    name: "Pasta de trigo",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "Probar solo si hay buena tolerancia al trigo.",
    tags: ["gluten", "porcion"],
  },
  {
    id: "food-017",
    name: "Maiz cocido",
    category: "Cereal",
    status: "testing",
    tolerance: 3,
    notes: "Probar como guarnicion en poca cantidad.",
    tags: ["sin gluten", "porcion"],
  },
  {
    id: "food-018",
    name: "Tortitas de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Snack simple cuando se busca algo neutro.",
    tags: ["snack", "sin gluten"],
  },
  {
    id: "food-019",
    name: "Galletas de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Revisar ingredientes si son comerciales.",
    tags: ["snack", "sin gluten", "procesado"],
  },
  {
    id: "food-020",
    name: "Ternera magra",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor con preparaciones sencillas y poca grasa.",
    tags: ["proteina", "salado"],
  },
  {
    id: "food-021",
    name: "Pavo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Opcion ligera si no lleva aditivos problematicos.",
    tags: ["proteina", "rapido"],
  },
  {
    id: "food-022",
    name: "Lomo de cerdo",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Elegir corte magro y cocinado simple.",
    tags: ["proteina", "salado"],
  },
  {
    id: "food-023",
    name: "Merluza",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Pescado blanco suave para comidas sencillas.",
    tags: ["pescado", "suave"],
  },
  {
    id: "food-024",
    name: "Salmon",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Puede resultar mas pesado por su grasa.",
    tags: ["pescado", "grasa saludable"],
  },
  {
    id: "food-025",
    name: "Atun natural",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Revisar sal, aceite y conservantes.",
    tags: ["pescado", "conserva"],
  },
  {
    id: "food-026",
    name: "Sardinas",
    category: "Proteina",
    status: "testing",
    tolerance: 3,
    notes: "Probar por su grasa y formato en conserva.",
    tags: ["pescado", "conserva"],
  },
  {
    id: "food-027",
    name: "Bacalao",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Controlar sal si es desalado o en conserva.",
    tags: ["pescado", "salado"],
  },
  {
    id: "food-028",
    name: "Gambas",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Proteina simple si se tolera marisco.",
    tags: ["marisco", "proteina"],
  },
  {
    id: "food-029",
    name: "Tofu firme",
    category: "Proteina",
    status: "testing",
    tolerance: 3,
    notes: "Probar racion pequena y revisar tolerancia a soja.",
    tags: ["soja", "vegetal", "fase prueba"],
  },
  {
    id: "food-030",
    name: "Jamon cocido",
    category: "Proteina",
    status: "caution",
    tolerance: 2,
    notes: "Revisar lactosa, azucares, almidones y aditivos.",
    tags: ["procesado", "proteina"],
  },
  {
    id: "food-031",
    name: "Jamon serrano",
    category: "Proteina",
    status: "caution",
    tolerance: 3,
    notes: "Controlar grasa, sal y cantidad.",
    tags: ["procesado", "salado"],
  },
  {
    id: "food-032",
    name: "Queso curado",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena; suele tener menos lactosa.",
    tags: ["lacteo", "porcion"],
  },
  {
    id: "food-033",
    name: "Claras de huevo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Proteina simple para desayunos o cenas.",
    tags: ["proteina", "desayuno"],
  },
  {
    id: "food-034",
    name: "Zanahoria",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Suele encajar bien cocida y en racion moderada.",
    tags: ["verdura", "suave"],
  },
  {
    id: "food-035",
    name: "Pepino",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar sin piel si resulta pesado.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-036",
    name: "Lechuga",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor en cantidad moderada si hay sensibilidad a crudos.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-037",
    name: "Espinaca",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocida o salteada en poca cantidad.",
    tags: ["verdura", "hoja verde"],
  },
  {
    id: "food-038",
    name: "Acelga",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Mejor cocida y con racion controlada.",
    tags: ["verdura", "hoja verde"],
  },
  {
    id: "food-039",
    name: "Pimiento rojo",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Puede tolerarse mejor cocinado y sin piel.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-040",
    name: "Pimiento verde",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocinado y en porcion pequena.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-041",
    name: "Tomate",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y tolerancia individual.",
    tags: ["verdura", "acido"],
  },
  {
    id: "food-042",
    name: "Berenjena",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Mejor bien cocinada y con poca grasa.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-043",
    name: "Judia verde",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocida y en racion pequena.",
    tags: ["verdura", "fase prueba"],
  },
  {
    id: "food-044",
    name: "Calabaza",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Controlar cantidad por carbohidrato fermentable.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-045",
    name: "Champinon",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser dificil en fases restrictivas.",
    tags: ["seta", "evitar"],
  },
  {
    id: "food-046",
    name: "Brocoli",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Puede generar gas; probar solo si hay estabilidad.",
    tags: ["crucifera", "gas"],
  },
  {
    id: "food-047",
    name: "Coliflor",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de fermentacion en muchas personas.",
    tags: ["crucifera", "evitar"],
  },
  {
    id: "food-048",
    name: "Repollo",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Puede aumentar gases e hinchazon.",
    tags: ["crucifera", "evitar"],
  },
  {
    id: "food-049",
    name: "Puerro",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Rico en compuestos fermentables.",
    tags: ["fodmap", "evitar"],
  },
  {
    id: "food-050",
    name: "Ajo",
    category: "Condimento",
    status: "avoid",
    tolerance: 1,
    notes: "Frecuente desencadenante en dietas restrictivas.",
    tags: ["fodmap", "evitar", "condimento"],
  },
  {
    id: "food-051",
    name: "Esparrago",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser dificil por fermentacion.",
    tags: ["verdura", "evitar"],
  },
  {
    id: "food-052",
    name: "Remolacha",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Probar racion pequena si hay buena tolerancia.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-053",
    name: "Rucula",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Hoja verde sencilla en cantidad moderada.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-054",
    name: "Apio",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Puede resultar fermentable segun cantidad.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-055",
    name: "Nabo",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocido y en racion pequena.",
    tags: ["verdura", "cocido"],
  },
  {
    id: "food-056",
    name: "Kiwi",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar una unidad pequena y observar transito.",
    tags: ["fruta", "transito"],
  },
  {
    id: "food-057",
    name: "Naranja",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y cantidad.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-058",
    name: "Mandarina",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-059",
    name: "Fresa",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Introducir en porcion controlada.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-060",
    name: "Arandanos",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar poca cantidad y revisar sintomas.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-061",
    name: "Uvas",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Controlar cantidad por carga de azucares.",
    tags: ["fruta", "azucar", "porcion"],
  },
  {
    id: "food-062",
    name: "Manzana",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser problematica en fases restrictivas.",
    tags: ["fruta", "fodmap", "evitar"],
  },
  {
    id: "food-063",
    name: "Pera",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Puede favorecer gases o hinchazon.",
    tags: ["fruta", "fodmap", "evitar"],
  },
  {
    id: "food-064",
    name: "Melocoton",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Reintroducir solo si hay estabilidad.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-065",
    name: "Mango",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Alta carga de azucares fermentables.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-066",
    name: "Melon",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad y observar.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-067",
    name: "Sandia",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Puede ser dificil por volumen y azucares.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-068",
    name: "Limon",
    category: "Fruta",
    status: "allowed",
    tolerance: 4,
    notes: "Uso pequeno como aderezo si no molesta la acidez.",
    tags: ["fruta", "condimento"],
  },
  {
    id: "food-069",
    name: "Papaya",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar racion pequena.",
    tags: ["fruta", "fase prueba"],
  },
  {
    id: "food-070",
    name: "Pina",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y cantidad.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-071",
    name: "Leche sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar si hay buena tolerancia a lacteos.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-072",
    name: "Leche de almendra",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar ingredientes y espesantes.",
    tags: ["bebida vegetal", "procesado"],
  },
  {
    id: "food-073",
    name: "Bebida de arroz",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar azucares anadidos.",
    tags: ["bebida vegetal", "sin lactosa"],
  },
  {
    id: "food-074",
    name: "Kefir sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Introducir con cautela por fermentacion.",
    tags: ["lacteo", "fermentado", "probio"],
  },
  {
    id: "food-075",
    name: "Queso fresco sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-076",
    name: "Mozzarella sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Controlar grasa y cantidad.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-077",
    name: "Yogur griego sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar si los fermentados encajan bien.",
    tags: ["lacteo", "sin lactosa", "fermentado"],
  },
  {
    id: "food-078",
    name: "Mantequilla",
    category: "Grasa",
    status: "caution",
    tolerance: 3,
    notes: "Usar poca cantidad por carga grasa.",
    tags: ["grasa", "lacteo"],
  },
  {
    id: "food-079",
    name: "Aceite de oliva",
    category: "Grasa",
    status: "allowed",
    tolerance: 5,
    notes: "Grasa principal en pequena cantidad.",
    tags: ["grasa", "condimento"],
  },
  {
    id: "food-080",
    name: "Aceitunas",
    category: "Grasa",
    status: "testing",
    tolerance: 3,
    notes: "Controlar sal y cantidad.",
    tags: ["grasa", "snack"],
  },
  {
    id: "food-081",
    name: "Almendras",
    category: "Fruto seco",
    status: "caution",
    tolerance: 2,
    notes: "Probar pocas unidades.",
    tags: ["fruto seco", "porcion"],
  },
  {
    id: "food-082",
    name: "Nueces",
    category: "Fruto seco",
    status: "testing",
    tolerance: 3,
    notes: "Controlar cantidad por grasa y fibra.",
    tags: ["fruto seco", "grasa"],
  },
  {
    id: "food-083",
    name: "Cacahuetes",
    category: "Fruto seco",
    status: "caution",
    tolerance: 2,
    notes: "Puede ser pesado; revisar tostado y sal.",
    tags: ["fruto seco", "snack"],
  },
  {
    id: "food-084",
    name: "Semillas de chia",
    category: "Semilla",
    status: "caution",
    tolerance: 2,
    notes: "Alta fibra; usar muy poca cantidad.",
    tags: ["semilla", "fibra"],
  },
  {
    id: "food-085",
    name: "Semillas de calabaza",
    category: "Semilla",
    status: "testing",
    tolerance: 3,
    notes: "Probar cantidad pequena.",
    tags: ["semilla", "snack"],
  },
  {
    id: "food-086",
    name: "Tahini",
    category: "Grasa",
    status: "caution",
    tolerance: 2,
    notes: "Pasta densa; probar poca cantidad.",
    tags: ["sesamo", "grasa"],
  },
  {
    id: "food-087",
    name: "Lentejas cocidas",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Puede generar gas; reintroducir solo si hay estabilidad.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-088",
    name: "Garbanzos cocidos",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de fermentacion.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-089",
    name: "Alubias blancas",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Suelen ser dificiles en fases restrictivas.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-090",
    name: "Guisantes",
    category: "Legumbre",
    status: "caution",
    tolerance: 2,
    notes: "Probar cantidad pequena si hay estabilidad.",
    tags: ["legumbre", "porcion"],
  },
  {
    id: "food-091",
    name: "Hummus",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Combina garbanzo y a menudo ajo.",
    tags: ["legumbre", "ajo", "evitar"],
  },
  {
    id: "food-092",
    name: "Edamame",
    category: "Legumbre",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad y observar sintomas.",
    tags: ["soja", "legumbre"],
  },
  {
    id: "food-093",
    name: "Agua",
    category: "Bebida",
    status: "allowed",
    tolerance: 5,
    notes: "Base de hidratacion.",
    tags: ["bebida", "base"],
  },
  {
    id: "food-094",
    name: "Cafe",
    category: "Bebida",
    status: "caution",
    tolerance: 2,
    notes: "Puede alterar transito o acidez.",
    tags: ["bebida", "estimulante"],
  },
  {
    id: "food-095",
    name: "Te verde",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Probar suave y no muy concentrado.",
    tags: ["bebida", "infusion"],
  },
  {
    id: "food-096",
    name: "Infusion de menta",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar si ayuda o empeora reflujo.",
    tags: ["bebida", "infusion"],
  },
  {
    id: "food-097",
    name: "Caldo casero",
    category: "Bebida",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor sin cebolla, ajo ni aditivos.",
    tags: ["caldo", "suave"],
  },
  {
    id: "food-098",
    name: "Salsa de tomate",
    category: "Condimento",
    status: "caution",
    tolerance: 2,
    notes: "Revisar ajo, cebolla, acidez y azucar.",
    tags: ["condimento", "procesado"],
  },
  {
    id: "food-099",
    name: "Chocolate negro",
    category: "Dulce",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad por grasa y estimulantes.",
    tags: ["dulce", "porcion"],
  },
  {
    id: "food-100",
    name: "Azucar blanco",
    category: "Dulce",
    status: "caution",
    tolerance: 2,
    notes: "Controlar cantidad y contexto de consumo.",
    tags: ["dulce", "azucar"],
  },
];

const suggestedServings = {
  "food-001": "120 g, equivale a un bol pequeno de arroz cocido.",
  "food-002": "120 g, equivale a un filete pequeno cocinado.",
  "food-003": "75 g, equivale a medio calabacin pequeno cocido.",
  "food-004": "1 unidad, huevo tamano M.",
  "food-005": "30 g, equivale a un cuarto de aguacate de tamano medio.",
  "food-006":
    "0 g, evitar en fase restrictiva; si se reintroduce, empezar con una cantidad minima cocinada.",
  "food-007": "125 g, equivale a un yogur individual pequeno.",
  "food-008": "80 g, equivale a medio platano pequeno poco maduro.",
  "food-009": "150 g, equivale a una patata mediana cocida.",
  "food-010": "70 g, equivale a medio boniato pequeno asado.",
  "food-011": "90 g, equivale a medio vaso de quinoa cocida.",
  "food-012": "40 g, equivale a unas 4 cucharadas de copos secos.",
  "food-013": "40 g, equivale a dos rebanadas pequenas.",
  "food-014":
    "0 g, evitar en fase restrictiva; reintroducir solo con media rebanada pequena.",
  "food-015": "75 g, equivale a un plato pequeno de pasta cocida.",
  "food-016": "60 g, equivale a una racion pequena de pasta cocida.",
  "food-017": "60 g, equivale a media taza de maiz cocido.",
  "food-018": "2 unidades, equivale a dos tortitas de arroz simples.",
  "food-019": "30 g, equivale a 4 o 5 galletas pequenas de arroz.",
  "food-020": "120 g, equivale a un filete pequeno de ternera magra.",
  "food-021": "120 g, equivale a un filete pequeno de pavo cocinado.",
  "food-022": "120 g, equivale a un corte pequeno de lomo magro.",
  "food-023": "150 g, equivale a un filete mediano de merluza.",
  "food-024": "120 g, equivale a un lomo pequeno de salmon.",
  "food-025": "80 g, equivale a una lata pequena escurrida.",
  "food-026": "60 g, equivale a dos sardinas pequenas.",
  "food-027": "120 g, equivale a una porcion pequena de bacalao desalado.",
  "food-028": "100 g, equivale a 8 o 10 gambas medianas.",
  "food-029": "80 g, equivale a media pieza pequena de tofu firme.",
  "food-030": "60 g, equivale a 2 o 3 lonchas de jamon cocido.",
  "food-031": "30 g, equivale a 2 lonchas finas de jamon serrano.",
  "food-032": "30 g, equivale a un dado pequeno de queso curado.",
  "food-033": "100 g, equivale a las claras de 3 huevos medianos.",
  "food-034": "80 g, equivale a una zanahoria mediana cocida.",
  "food-035": "60 g, equivale a medio pepino pequeno sin piel.",
  "food-036": "40 g, equivale a un bol pequeno de hojas de lechuga.",
  "food-037": "60 g, equivale a un punado grande de espinaca cocida.",
  "food-038": "70 g, equivale a media taza de acelga cocida.",
  "food-039": "60 g, equivale a medio pimiento rojo pequeno cocinado.",
  "food-040": "50 g, equivale a medio pimiento verde pequeno cocinado.",
  "food-041": "80 g, equivale a un tomate pequeno.",
  "food-042": "75 g, equivale a media berenjena pequena cocinada.",
  "food-043": "60 g, equivale a un punado pequeno de judias verdes cocidas.",
  "food-044": "75 g, equivale a media taza de calabaza cocida en dados.",
  "food-045":
    "0 g, evitar en fase restrictiva; reintroducir solo en cantidad minima.",
  "food-046": "40 g, equivale a 2 o 3 arbolitos pequenos de brocoli cocido.",
  "food-047":
    "0 g, evitar en fase restrictiva; reintroducir solo con una cantidad minima.",
  "food-048":
    "0 g, evitar en fase restrictiva; reintroducir solo con una cantidad minima.",
  "food-049": "0 g, evitar en fase restrictiva; especialmente la parte blanca.",
  "food-050":
    "0 g, evitar como ingrediente; usar aceite infusionado si se busca sabor.",
  "food-051":
    "0 g, evitar en fase restrictiva; reintroducir solo si hay estabilidad.",
  "food-052": "40 g, equivale a 2 o 3 rodajas pequenas de remolacha cocida.",
  "food-053": "30 g, equivale a un punado pequeno de rucula.",
  "food-054": "20 g, equivale a un tallo pequeno de apio.",
  "food-055": "60 g, equivale a media taza de nabo cocido.",
  "food-056": "1 unidad, kiwi pequeno.",
  "food-057": "1 unidad, naranja pequena.",
  "food-058": "1 unidad, mandarina pequena.",
  "food-059": "80 g, equivale a un punado de fresas.",
  "food-060": "40 g, equivale a un punado pequeno de arandanos.",
  "food-061": "50 g, equivale a 8 o 10 uvas.",
  "food-062":
    "0 g, evitar en fase restrictiva; reintroducir solo con un trozo pequeno.",
  "food-063":
    "0 g, evitar en fase restrictiva; reintroducir solo con un trozo pequeno.",
  "food-064":
    "0 g, evitar en fase restrictiva; reintroducir solo con un trozo pequeno.",
  "food-065":
    "0 g, evitar en fase restrictiva; reintroducir solo con un trozo pequeno.",
  "food-066": "80 g, equivale a una tajada pequena de melon.",
  "food-067": "0 g, evitar en fase restrictiva por volumen y azucares.",
  "food-068": "10 g, equivale a una cucharada de zumo de limon como aderezo.",
  "food-069": "100 g, equivale a media taza de papaya en dados.",
  "food-070": "80 g, equivale a media taza de pina en dados.",
  "food-071": "200 ml, equivale a un vaso pequeno de leche sin lactosa.",
  "food-072": "200 ml, equivale a un vaso pequeno de bebida de almendra.",
  "food-073": "200 ml, equivale a un vaso pequeno de bebida de arroz.",
  "food-074": "125 g, equivale a un vaso individual pequeno de kefir.",
  "food-075": "60 g, equivale a medio envase pequeno de queso fresco.",
  "food-076": "50 g, equivale a media bola pequena de mozzarella.",
  "food-077": "125 g, equivale a un yogur individual pequeno.",
  "food-078": "10 g, equivale a una cucharadita colmada de mantequilla.",
  "food-079": "10 ml, equivale a una cucharada rasa de aceite de oliva.",
  "food-080": "30 g, equivale a 6 u 8 aceitunas.",
  "food-081": "15 g, equivale a 10 o 12 almendras.",
  "food-082": "20 g, equivale a 4 medias nueces.",
  "food-083": "15 g, equivale a un punado pequeno de cacahuetes.",
  "food-084": "5 g, equivale a una cucharadita de semillas de chia.",
  "food-085": "15 g, equivale a una cucharada de semillas de calabaza.",
  "food-086": "10 g, equivale a una cucharadita colmada de tahini.",
  "food-087":
    "0 g, evitar en fase restrictiva; reintroducir solo con 1 o 2 cucharadas.",
  "food-088":
    "0 g, evitar en fase restrictiva; reintroducir solo con 1 o 2 cucharadas.",
  "food-089":
    "0 g, evitar en fase restrictiva; reintroducir solo con 1 o 2 cucharadas.",
  "food-090": "30 g, equivale a 2 cucharadas de guisantes cocidos.",
  "food-091":
    "0 g, evitar en fase restrictiva; si se prueba, empezar con una cucharadita.",
  "food-092": "40 g, equivale a un punado pequeno de edamame.",
  "food-093": "250 ml, equivale a un vaso de agua.",
  "food-094": "100 ml, equivale a una taza pequena de cafe.",
  "food-095": "200 ml, equivale a una taza de te verde suave.",
  "food-096": "200 ml, equivale a una taza de infusion de menta.",
  "food-097": "200 ml, equivale a una taza de caldo casero.",
  "food-098": "30 g, equivale a 2 cucharadas de salsa de tomate.",
  "food-099": "10 g, equivale a 1 o 2 onzas pequenas de chocolate negro.",
  "food-100": "5 g, equivale a una cucharadita rasa de azucar blanco.",
};

const recipes = [
  {
    id: "recipe-001",
    name: "Bowl de arroz con pollo",
    description: "Comida base, sencilla y facil de ajustar por tolerancia.",
    ingredients: [
      "Arroz blanco cocido",
      "Pechuga de pollo",
      "Aceite de oliva",
      "Sal",
      "Zanahoria cocida opcional",
    ],
    steps: [
      "Cocer el arroz hasta que quede suelto.",
      "Dorar el pollo con poco aceite.",
      "Combinar y ajustar sal al final.",
    ],
    tags: ["comida", "base", "sin gluten"],
    prepTimeMinutes: 25,
    rating: 5,
  },
  {
    id: "recipe-002",
    name: "Tortilla suave",
    description: "Cena rapida con pocos ingredientes y buena saciedad.",
    ingredients: ["Huevos", "Sal", "Aceite de oliva"],
    steps: [
      "Batir los huevos con una pizca de sal.",
      "Cuajar a fuego medio con poco aceite.",
      "Servir con arroz o verdura tolerada.",
    ],
    tags: ["cena", "rapida", "proteina"],
    prepTimeMinutes: 10,
    rating: 4,
  },
  {
    id: "recipe-003",
    name: "Crema simple de calabacin",
    description: "Receta en fase de prueba para raciones pequenas.",
    ingredients: ["Calabacin pelado", "Agua", "Sal", "Aceite de oliva"],
    steps: [
      "Cocer el calabacin pelado hasta que este tierno.",
      "Triturar con parte del agua de coccion.",
      "Anadir aceite de oliva al servir.",
    ],
    tags: ["verdura", "fase prueba", "suave"],
    prepTimeMinutes: 20,
    rating: 3,
  },
];

if (foods.length !== 100) {
  throw new Error(`Expected 100 seed foods, received ${foods.length}.`);
}

const foodsWithoutSuggestedServing = foods.filter(
  (food) => !food.suggestedServing && !suggestedServings[food.id],
);

if (foodsWithoutSuggestedServing.length > 0) {
  throw new Error(
    `Missing suggested serving for foods: ${foodsWithoutSuggestedServing
      .map((food) => food.id)
      .join(", ")}.`,
  );
}

function getSuggestedServing(food) {
  return food.suggestedServing ?? suggestedServings[food.id];
}

const seedFoodIds = foods.map((food) => food.id);
const result = await prisma.food.createMany({
  data: foods.map((food) => ({
    ...food,
    createdAt: seedTimestamp,
    suggestedServing: getSuggestedServing(food),
    updatedAt: seedTimestamp,
  })),
  skipDuplicates: true,
});

const seededCount = await prisma.food.count({
  where: {
    id: {
      in: seedFoodIds,
    },
  },
});
const totalCount = await prisma.food.count();

console.log(
  `Food seed completed. Inserted ${result.count}, seed records ${seededCount}/100, total foods ${totalCount}.`,
);

for (const food of foods) {
  await prisma.food.update({
    data: {
      suggestedServing: getSuggestedServing(food),
    },
    where: {
      id: food.id,
    },
  });
}

const recipeResult = await prisma.recipe.createMany({
  data: recipes.map((recipe) => ({
    ...recipe,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  })),
  skipDuplicates: true,
});

const seededRecipesCount = await prisma.recipe.count({
  where: {
    id: {
      in: recipes.map((recipe) => recipe.id),
    },
  },
});

console.log(
  `Recipe seed completed. Inserted ${recipeResult.count}, seed records ${seededRecipesCount}/${recipes.length}.`,
);

for (const user of users) {
  await prisma.appUser.upsert({
    where: {
      username: user.username,
    },
    update: {
      displayName: user.displayName,
      email: user.email,
      passwordHash: hashPassword(user.password),
      role: user.role,
    },
    create: {
      displayName: user.displayName,
      email: user.email,
      passwordHash: hashPassword(user.password),
      role: user.role,
      username: user.username,
    },
  });
}

const seededUsersCount = await prisma.appUser.count({
  where: {
    username: {
      in: users.map((user) => user.username),
    },
  },
});

console.log(`User seed completed. Seed users ${seededUsersCount}/3.`);

await prisma.$disconnect();
