import { PrismaClient } from "@prisma/client";
import { config } from "dotenv";

config({ path: ".env.local" });
config();

const prisma = new PrismaClient();

const seedTimestamp = new Date("2026-06-10T00:00:00.000Z");

const foods = [
  {
    id: "food-001",
    name: "Arroz blanco",
    category: "Cereal",
    status: "allowed",
    tolerance: 5,
    notes: "Base neutra para comidas simples.",
    tags: ["bajo residuo", "sin gluten", "base"],
  },
  {
    id: "food-002",
    name: "Pechuga de pollo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Mejor a la plancha, horno o cocida con poca grasa.",
    tags: ["proteina", "rapido", "salado"],
  },
  {
    id: "food-003",
    name: "Calabacin",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar sin piel y en racion pequena.",
    tags: ["verdura", "fase prueba"],
  },
  {
    id: "food-004",
    name: "Huevo",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Util para desayunos y cenas rapidas.",
    tags: ["proteina", "desayuno"],
  },
  {
    id: "food-005",
    name: "Aguacate",
    category: "Grasa",
    status: "caution",
    tolerance: 2,
    notes: "Puede ser pesado; revisar cantidad y momento del dia.",
    tags: ["grasa", "porcion controlada"],
  },
  {
    id: "food-006",
    name: "Cebolla",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de sintomas en fases restrictivas.",
    tags: ["fodmap", "evitar"],
  },
  {
    id: "food-007",
    name: "Yogur sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Introducir solo si hay buena tolerancia a lacteos.",
    tags: ["lacteo", "probio"],
  },
  {
    id: "food-008",
    name: "Platano verde",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Mejor en pequena cantidad y no demasiado maduro.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-009",
    name: "Patata cocida",
    category: "Tuberculo",
    status: "allowed",
    tolerance: 5,
    notes: "Opcion simple para comidas suaves.",
    tags: ["base", "sin gluten", "suave"],
  },
  {
    id: "food-010",
    name: "Boniato",
    category: "Tuberculo",
    status: "testing",
    tolerance: 3,
    notes: "Probar en racion pequena por su carga de carbohidrato.",
    tags: ["tuberculo", "porcion"],
  },
  {
    id: "food-011",
    name: "Quinoa",
    category: "Cereal",
    status: "testing",
    tolerance: 3,
    notes: "Lavar bien y probar como guarnicion pequena.",
    tags: ["sin gluten", "guarnicion"],
  },
  {
    id: "food-012",
    name: "Avena",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "La tolerancia puede variar mucho segun cantidad.",
    tags: ["fibra", "desayuno", "porcion"],
  },
  {
    id: "food-013",
    name: "Pan blanco",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "Revisar tolerancia individual y tipo de harina.",
    tags: ["gluten", "procesado"],
  },
  {
    id: "food-014",
    name: "Pan integral",
    category: "Cereal",
    status: "avoid",
    tolerance: 1,
    notes: "Puede ser mas fermentable por fibra y trigo.",
    tags: ["gluten", "fibra", "evitar"],
  },
  {
    id: "food-015",
    name: "Pasta de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Alternativa sencilla a pasta de trigo.",
    tags: ["sin gluten", "base"],
  },
  {
    id: "food-016",
    name: "Pasta de trigo",
    category: "Cereal",
    status: "caution",
    tolerance: 2,
    notes: "Probar solo si hay buena tolerancia al trigo.",
    tags: ["gluten", "porcion"],
  },
  {
    id: "food-017",
    name: "Maiz cocido",
    category: "Cereal",
    status: "testing",
    tolerance: 3,
    notes: "Probar como guarnicion en poca cantidad.",
    tags: ["sin gluten", "porcion"],
  },
  {
    id: "food-018",
    name: "Tortitas de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Snack simple cuando se busca algo neutro.",
    tags: ["snack", "sin gluten"],
  },
  {
    id: "food-019",
    name: "Galletas de arroz",
    category: "Cereal",
    status: "allowed",
    tolerance: 4,
    notes: "Revisar ingredientes si son comerciales.",
    tags: ["snack", "sin gluten", "procesado"],
  },
  {
    id: "food-020",
    name: "Ternera magra",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor con preparaciones sencillas y poca grasa.",
    tags: ["proteina", "salado"],
  },
  {
    id: "food-021",
    name: "Pavo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Opcion ligera si no lleva aditivos problematicos.",
    tags: ["proteina", "rapido"],
  },
  {
    id: "food-022",
    name: "Lomo de cerdo",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Elegir corte magro y cocinado simple.",
    tags: ["proteina", "salado"],
  },
  {
    id: "food-023",
    name: "Merluza",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Pescado blanco suave para comidas sencillas.",
    tags: ["pescado", "suave"],
  },
  {
    id: "food-024",
    name: "Salmon",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Puede resultar mas pesado por su grasa.",
    tags: ["pescado", "grasa saludable"],
  },
  {
    id: "food-025",
    name: "Atun natural",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Revisar sal, aceite y conservantes.",
    tags: ["pescado", "conserva"],
  },
  {
    id: "food-026",
    name: "Sardinas",
    category: "Proteina",
    status: "testing",
    tolerance: 3,
    notes: "Probar por su grasa y formato en conserva.",
    tags: ["pescado", "conserva"],
  },
  {
    id: "food-027",
    name: "Bacalao",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Controlar sal si es desalado o en conserva.",
    tags: ["pescado", "salado"],
  },
  {
    id: "food-028",
    name: "Gambas",
    category: "Proteina",
    status: "allowed",
    tolerance: 4,
    notes: "Proteina simple si se tolera marisco.",
    tags: ["marisco", "proteina"],
  },
  {
    id: "food-029",
    name: "Tofu firme",
    category: "Proteina",
    status: "testing",
    tolerance: 3,
    notes: "Probar racion pequena y revisar tolerancia a soja.",
    tags: ["soja", "vegetal", "fase prueba"],
  },
  {
    id: "food-030",
    name: "Jamon cocido",
    category: "Proteina",
    status: "caution",
    tolerance: 2,
    notes: "Revisar lactosa, azucares, almidones y aditivos.",
    tags: ["procesado", "proteina"],
  },
  {
    id: "food-031",
    name: "Jamon serrano",
    category: "Proteina",
    status: "caution",
    tolerance: 3,
    notes: "Controlar grasa, sal y cantidad.",
    tags: ["procesado", "salado"],
  },
  {
    id: "food-032",
    name: "Queso curado",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena; suele tener menos lactosa.",
    tags: ["lacteo", "porcion"],
  },
  {
    id: "food-033",
    name: "Claras de huevo",
    category: "Proteina",
    status: "allowed",
    tolerance: 5,
    notes: "Proteina simple para desayunos o cenas.",
    tags: ["proteina", "desayuno"],
  },
  {
    id: "food-034",
    name: "Zanahoria",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Suele encajar bien cocida y en racion moderada.",
    tags: ["verdura", "suave"],
  },
  {
    id: "food-035",
    name: "Pepino",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar sin piel si resulta pesado.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-036",
    name: "Lechuga",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor en cantidad moderada si hay sensibilidad a crudos.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-037",
    name: "Espinaca",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocida o salteada en poca cantidad.",
    tags: ["verdura", "hoja verde"],
  },
  {
    id: "food-038",
    name: "Acelga",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Mejor cocida y con racion controlada.",
    tags: ["verdura", "hoja verde"],
  },
  {
    id: "food-039",
    name: "Pimiento rojo",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Puede tolerarse mejor cocinado y sin piel.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-040",
    name: "Pimiento verde",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocinado y en porcion pequena.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-041",
    name: "Tomate",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y tolerancia individual.",
    tags: ["verdura", "acido"],
  },
  {
    id: "food-042",
    name: "Berenjena",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Mejor bien cocinada y con poca grasa.",
    tags: ["verdura", "cocinado"],
  },
  {
    id: "food-043",
    name: "Judia verde",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocida y en racion pequena.",
    tags: ["verdura", "fase prueba"],
  },
  {
    id: "food-044",
    name: "Calabaza",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Controlar cantidad por carbohidrato fermentable.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-045",
    name: "Champinon",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser dificil en fases restrictivas.",
    tags: ["seta", "evitar"],
  },
  {
    id: "food-046",
    name: "Brocoli",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Puede generar gas; probar solo si hay estabilidad.",
    tags: ["crucifera", "gas"],
  },
  {
    id: "food-047",
    name: "Coliflor",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de fermentacion en muchas personas.",
    tags: ["crucifera", "evitar"],
  },
  {
    id: "food-048",
    name: "Repollo",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Puede aumentar gases e hinchazon.",
    tags: ["crucifera", "evitar"],
  },
  {
    id: "food-049",
    name: "Puerro",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Rico en compuestos fermentables.",
    tags: ["fodmap", "evitar"],
  },
  {
    id: "food-050",
    name: "Ajo",
    category: "Condimento",
    status: "avoid",
    tolerance: 1,
    notes: "Frecuente desencadenante en dietas restrictivas.",
    tags: ["fodmap", "evitar", "condimento"],
  },
  {
    id: "food-051",
    name: "Esparrago",
    category: "Verdura",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser dificil por fermentacion.",
    tags: ["verdura", "evitar"],
  },
  {
    id: "food-052",
    name: "Remolacha",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Probar racion pequena si hay buena tolerancia.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-053",
    name: "Rucula",
    category: "Verdura",
    status: "allowed",
    tolerance: 4,
    notes: "Hoja verde sencilla en cantidad moderada.",
    tags: ["verdura", "crudo"],
  },
  {
    id: "food-054",
    name: "Apio",
    category: "Verdura",
    status: "caution",
    tolerance: 2,
    notes: "Puede resultar fermentable segun cantidad.",
    tags: ["verdura", "porcion"],
  },
  {
    id: "food-055",
    name: "Nabo",
    category: "Verdura",
    status: "testing",
    tolerance: 3,
    notes: "Probar cocido y en racion pequena.",
    tags: ["verdura", "cocido"],
  },
  {
    id: "food-056",
    name: "Kiwi",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar una unidad pequena y observar transito.",
    tags: ["fruta", "transito"],
  },
  {
    id: "food-057",
    name: "Naranja",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y cantidad.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-058",
    name: "Mandarina",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-059",
    name: "Fresa",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Introducir en porcion controlada.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-060",
    name: "Arandanos",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar poca cantidad y revisar sintomas.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-061",
    name: "Uvas",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Controlar cantidad por carga de azucares.",
    tags: ["fruta", "azucar", "porcion"],
  },
  {
    id: "food-062",
    name: "Manzana",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Suele ser problematica en fases restrictivas.",
    tags: ["fruta", "fodmap", "evitar"],
  },
  {
    id: "food-063",
    name: "Pera",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Puede favorecer gases o hinchazon.",
    tags: ["fruta", "fodmap", "evitar"],
  },
  {
    id: "food-064",
    name: "Melocoton",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Reintroducir solo si hay estabilidad.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-065",
    name: "Mango",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Alta carga de azucares fermentables.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-066",
    name: "Melon",
    category: "Fruta",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad y observar.",
    tags: ["fruta", "porcion"],
  },
  {
    id: "food-067",
    name: "Sandia",
    category: "Fruta",
    status: "avoid",
    tolerance: 1,
    notes: "Puede ser dificil por volumen y azucares.",
    tags: ["fruta", "evitar"],
  },
  {
    id: "food-068",
    name: "Limon",
    category: "Fruta",
    status: "allowed",
    tolerance: 4,
    notes: "Uso pequeno como aderezo si no molesta la acidez.",
    tags: ["fruta", "condimento"],
  },
  {
    id: "food-069",
    name: "Papaya",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Probar racion pequena.",
    tags: ["fruta", "fase prueba"],
  },
  {
    id: "food-070",
    name: "Pina",
    category: "Fruta",
    status: "testing",
    tolerance: 3,
    notes: "Revisar acidez y cantidad.",
    tags: ["fruta", "acido"],
  },
  {
    id: "food-071",
    name: "Leche sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar si hay buena tolerancia a lacteos.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-072",
    name: "Leche de almendra",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar ingredientes y espesantes.",
    tags: ["bebida vegetal", "procesado"],
  },
  {
    id: "food-073",
    name: "Bebida de arroz",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar azucares anadidos.",
    tags: ["bebida vegetal", "sin lactosa"],
  },
  {
    id: "food-074",
    name: "Kefir sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Introducir con cautela por fermentacion.",
    tags: ["lacteo", "fermentado", "probio"],
  },
  {
    id: "food-075",
    name: "Queso fresco sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar porcion pequena.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-076",
    name: "Mozzarella sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Controlar grasa y cantidad.",
    tags: ["lacteo", "sin lactosa"],
  },
  {
    id: "food-077",
    name: "Yogur griego sin lactosa",
    category: "Lacteo",
    status: "testing",
    tolerance: 3,
    notes: "Probar si los fermentados encajan bien.",
    tags: ["lacteo", "sin lactosa", "fermentado"],
  },
  {
    id: "food-078",
    name: "Mantequilla",
    category: "Grasa",
    status: "caution",
    tolerance: 3,
    notes: "Usar poca cantidad por carga grasa.",
    tags: ["grasa", "lacteo"],
  },
  {
    id: "food-079",
    name: "Aceite de oliva",
    category: "Grasa",
    status: "allowed",
    tolerance: 5,
    notes: "Grasa principal en pequena cantidad.",
    tags: ["grasa", "condimento"],
  },
  {
    id: "food-080",
    name: "Aceitunas",
    category: "Grasa",
    status: "testing",
    tolerance: 3,
    notes: "Controlar sal y cantidad.",
    tags: ["grasa", "snack"],
  },
  {
    id: "food-081",
    name: "Almendras",
    category: "Fruto seco",
    status: "caution",
    tolerance: 2,
    notes: "Probar pocas unidades.",
    tags: ["fruto seco", "porcion"],
  },
  {
    id: "food-082",
    name: "Nueces",
    category: "Fruto seco",
    status: "testing",
    tolerance: 3,
    notes: "Controlar cantidad por grasa y fibra.",
    tags: ["fruto seco", "grasa"],
  },
  {
    id: "food-083",
    name: "Cacahuetes",
    category: "Fruto seco",
    status: "caution",
    tolerance: 2,
    notes: "Puede ser pesado; revisar tostado y sal.",
    tags: ["fruto seco", "snack"],
  },
  {
    id: "food-084",
    name: "Semillas de chia",
    category: "Semilla",
    status: "caution",
    tolerance: 2,
    notes: "Alta fibra; usar muy poca cantidad.",
    tags: ["semilla", "fibra"],
  },
  {
    id: "food-085",
    name: "Semillas de calabaza",
    category: "Semilla",
    status: "testing",
    tolerance: 3,
    notes: "Probar cantidad pequena.",
    tags: ["semilla", "snack"],
  },
  {
    id: "food-086",
    name: "Tahini",
    category: "Grasa",
    status: "caution",
    tolerance: 2,
    notes: "Pasta densa; probar poca cantidad.",
    tags: ["sesamo", "grasa"],
  },
  {
    id: "food-087",
    name: "Lentejas cocidas",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Puede generar gas; reintroducir solo si hay estabilidad.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-088",
    name: "Garbanzos cocidos",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Alta probabilidad de fermentacion.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-089",
    name: "Alubias blancas",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Suelen ser dificiles en fases restrictivas.",
    tags: ["legumbre", "evitar"],
  },
  {
    id: "food-090",
    name: "Guisantes",
    category: "Legumbre",
    status: "caution",
    tolerance: 2,
    notes: "Probar cantidad pequena si hay estabilidad.",
    tags: ["legumbre", "porcion"],
  },
  {
    id: "food-091",
    name: "Hummus",
    category: "Legumbre",
    status: "avoid",
    tolerance: 1,
    notes: "Combina garbanzo y a menudo ajo.",
    tags: ["legumbre", "ajo", "evitar"],
  },
  {
    id: "food-092",
    name: "Edamame",
    category: "Legumbre",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad y observar sintomas.",
    tags: ["soja", "legumbre"],
  },
  {
    id: "food-093",
    name: "Agua",
    category: "Bebida",
    status: "allowed",
    tolerance: 5,
    notes: "Base de hidratacion.",
    tags: ["bebida", "base"],
  },
  {
    id: "food-094",
    name: "Cafe",
    category: "Bebida",
    status: "caution",
    tolerance: 2,
    notes: "Puede alterar transito o acidez.",
    tags: ["bebida", "estimulante"],
  },
  {
    id: "food-095",
    name: "Te verde",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Probar suave y no muy concentrado.",
    tags: ["bebida", "infusion"],
  },
  {
    id: "food-096",
    name: "Infusion de menta",
    category: "Bebida",
    status: "testing",
    tolerance: 3,
    notes: "Revisar si ayuda o empeora reflujo.",
    tags: ["bebida", "infusion"],
  },
  {
    id: "food-097",
    name: "Caldo casero",
    category: "Bebida",
    status: "allowed",
    tolerance: 4,
    notes: "Mejor sin cebolla, ajo ni aditivos.",
    tags: ["caldo", "suave"],
  },
  {
    id: "food-098",
    name: "Salsa de tomate",
    category: "Condimento",
    status: "caution",
    tolerance: 2,
    notes: "Revisar ajo, cebolla, acidez y azucar.",
    tags: ["condimento", "procesado"],
  },
  {
    id: "food-099",
    name: "Chocolate negro",
    category: "Dulce",
    status: "caution",
    tolerance: 2,
    notes: "Probar poca cantidad por grasa y estimulantes.",
    tags: ["dulce", "porcion"],
  },
  {
    id: "food-100",
    name: "Azucar blanco",
    category: "Dulce",
    status: "caution",
    tolerance: 2,
    notes: "Controlar cantidad y contexto de consumo.",
    tags: ["dulce", "azucar"],
  },
];

if (foods.length !== 100) {
  throw new Error(`Expected 100 seed foods, received ${foods.length}.`);
}

const seedFoodIds = foods.map((food) => food.id);
const result = await prisma.food.createMany({
  data: foods.map((food) => ({
    ...food,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  })),
  skipDuplicates: true,
});

const seededCount = await prisma.food.count({
  where: {
    id: {
      in: seedFoodIds,
    },
  },
});
const totalCount = await prisma.food.count();

console.log(
  `Food seed completed. Inserted ${result.count}, seed records ${seededCount}/100, total foods ${totalCount}.`,
);

await prisma.$disconnect();
